[package]
name = "hashname"
version = "1.0.1"
edition = "2021"
authors = ["xxkfqz <xxkfqz@gmail.com"]
license-file = "LICENSE"
repository = "https://github.com/xxkfqz/hashname"
description = "Utility for renaming files to their SHA256 hash"

[dependencies]
clap = {
    version = "4.6.6",
    features = [
        "derive",
        "std",
        "wrap_help"
    ]
}
sha2 = "0.11.0"
base16ct = "1.0.0"
rayon = "1.12.0"

[profile.release]
opt-level = 3
debug = false
rpath = true
lto = true
debug-assertions = false
codegen-units = 16
panic = "abort"
incremental = false
overflow-checks = false
strip = true
