[package]
name = "hashname"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = {
    version = "4.6.4",
    features = [
        "derive",
        "std",
        "wrap_help"
    ]
}
sha2 = "0.11"
base16ct = "1.0.0"
rayon = "1.12.0"

[profile.release]
opt-level = 3
debug = false
rpath = true
lto = true
debug-assertions = false
codegen-units = 16
panic = "abort"
incremental = false
overflow-checks = false
strip = true
